---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en Azure para proporcionar operaciones confiables.  Para obtener el mejor rendimiento, no configure su sistema con los valores máximos. 
---
= Límites de almacenamiento para Cloud Volumes ONTAP en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones confiables.  Para obtener el mejor rendimiento, no configure su sistema con los valores máximos.



== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema para un sistema Cloud Volumes ONTAP está determinada por su licencia. La capacidad máxima del sistema incluye almacenamiento basado en disco más almacenamiento de objetos utilizado para la clasificación de datos.

NetApp no admite exceder el límite de capacidad del sistema. Si alcanza el límite de capacidad autorizado, BlueXP muestra un mensaje de acción requerida y le impide agregar más discos.

.Límite de capacidad para licencias basadas en capacidad
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos. La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube. Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles. Consulte la https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Documentación de Azure para discos administrados"^] y https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Documentación de Azure para el almacenamiento de blobs"^] .

Límites de capacidad para otros tipos de licencias::


[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explorar | 2 TiB (la estratificación de datos no es compatible con Explore) 


| Estándar PAYGO | 10 TiB 


| Prima de pago por uso | 368 TiB 


| Licencia basada en nodos | 2 PiB (requiere múltiples licencias) 
|===
.Para HA, ¿el límite de capacidad de la licencia es por nodo o para todo el par de HA?
El límite de capacidad es para todo el par HA. No es por nodo. Por ejemplo, si utilizas la licencia Premium, podrás tener hasta 368 TiB de capacidad entre ambos nodos.



== Límites agregados

Cloud Volumes ONTAP utiliza el almacenamiento de Azure como discos y los agrupa en _agregados_.  Los agregados proporcionan almacenamiento a los volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados | Igual que el límite del disco 


| Tamaño máximo del agregado ^1^ | 384 TiB de capacidad bruta para un solo nodo ^2^ 352 TiB de capacidad bruta para un solo nodo con PAYGO 96 TiB de capacidad bruta para pares de alta disponibilidad con blob de página 384 TiB de capacidad bruta para pares de alta disponibilidad con discos administrados 


| Discos por agregado | 1-12 ^3^ 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. El límite de capacidad agregada se basa en los discos que componen el agregado.  El límite no incluye el almacenamiento de objetos utilizado para la clasificación de datos.
. Si se utilizan licencias basadas en nodos, se requieren dos licencias BYOL para alcanzar los 384 TiB.
. Todos los discos de un agregado deben tener el mismo tamaño.




== Límites de disco y niveles según el tamaño de la máquina virtual

Los límites de capacidad varían según el tamaño de la máquina virtual y el tipo de sistema (nodo único o par HA).

Las notas a continuación explican los números en las tablas:

* Los límites del disco son específicos de los discos que contienen datos del usuario.
+
Los límites no incluyen el disco raíz, el disco central y VNVRAM.

* Puede ver la capacidad máxima del sistema cuando usa solo discos y cuando usa discos y niveles de datos fríos en el almacenamiento de objetos.
* Los sistemas de nodo único y de alta disponibilidad que utilizan discos administrados tienen un máximo de 32 TiB por disco.  La cantidad de discos admitidos varía según el tamaño de la máquina virtual.
* Los sistemas HA que utilizan blobs de página tienen un máximo de 8 TiB por blob de página.  La cantidad de discos admitidos varía según el tamaño de la máquina virtual.
* El límite basado en disco de 896 TiB que se indica para sistemas de nodo único con ciertos tamaños de VM es el límite _probado_.




=== Límites para diferentes modos de implementación de licencias basadas en capacidad

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que utilizan un paquete de licencias basado en capacidad. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Obtenga más información sobre las opciones de licencia de Cloud Volumes ONTAP"^] .


NOTE: Para conocer los límites de capacidad máxima del sistema y de capacidad de niveles de datos para un solo nodo, pares de alta disponibilidad en una sola zona de disponibilidad con blobs de página y pares de alta disponibilidad en una o varias zonas de disponibilidad con discos administrados compartidos, consulte<<cap-license-azure>> .



==== Nodo único

[cols="14,20,31"]
|===
| Tamaño de VM | Máximo de discos de datos por nodo | Capacidad máxima del sistema solo con discos 


| DS4_v2 | 29 | 896 TiB 


| DS5_v2 | 61 | 896 TiB 


| DS13_v2 | 29 | 896 TiB 


| DS14_v2 | 61 | 896 TiB 


| DS15_v2 | 61 | 896 TiB 


| E4s_v3 | 5 | 160 TiB 


| E8s_v3 | 13 | 416 TiB 


| E32s_v3 | 29 | 896 TiB 


| E48s_v3 | 29 | 896 TiB 


| E64is_v3 | 29 | 896 TiB 


| E4ds_v4 | 5 | 160 TiB 


| E8ds_v4 | 13 | 416 TiB 


| E32ds_v4 | 29 | 896 TiB 


| E48ds_v4 | 29 | 896 TiB 


| E80ids_v4 | 61 | 896 TiB 


| E4ds_v5 | 5 | 160 TiB 


| E8ds_v5 | 13 | 416 TiB 


| E20ds_v5 | 29 | 896 TiB 


| E32ds_v5 | 29 | 896 TiB 


| E48ds_v5 | 29 | 896 TiB 


| E64ds_v5 | 29 | 896 TiB 


| L8s_v3 | 12 | 384 TiB 


| L16s_v3 | 28 | 896 TiB 


| L32s_v3 | 28 | 896 TiB 


| L48s_v3 | 28 | 896 TiB 


| L64s_v3 | 28 | 896 TiB 
|===


==== Pares de alta disponibilidad en una única zona de disponibilidad con blobs de página

[cols="14,20,31"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA | Capacidad máxima del sistema solo con discos 


| DS4_v2 | 29 | 232 TiB 


| DS5_v2 | 61 | 488 TiB 


| DS13_v2 | 29 | 232 TiB 


| DS14_v2 | 61 | 488 TiB 


| DS15_v2 | 61 | 488 TiB 


| E8s_v3 | 13 | 104 TiB 


| E48s_v3 | 29 | 232 TiB 


| E8ds_v4 | 13 | 104 TiB 


| E32ds_v4 | 29 | 232 TiB 


| E48ds_v4 | 29 | 232 TiB 


| E80ids_v4 | 61 | 488 TiB 
|===


==== Pares de alta disponibilidad en una única zona de disponibilidad con discos administrados compartidos

[cols="14,20,31"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA | Capacidad máxima del sistema solo con discos 


| E8ds_v4 | 12 | 384 TiB 


| E32ds_v4 | 28 | 896 TiB 


| E48ds_v4 | 28 | 896 TiB 


| E80ids_v4 | 28 | 896 TiB 


| E8ds_v5 | 12 | 384 TiB 


| E20ds_v5 | 28 | 896 TiB 


| E32ds_v5 | 28 | 896 TiB 


| E48ds_v5 | 28 | 896 TiB 


| E64ds_v5 | 28 | 896 TiB 


| L16s_v3 | 28 | 896 TiB 


| L32s_v3 | 28 | 896 TiB 


| L48s_v3 | 28 | 896 TiB 


| L64s_v3 | 28 | 896 TiB 
|===


==== Pares de alta disponibilidad en múltiples zonas de disponibilidad con discos administrados compartidos

[cols="14,20,31"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA | Capacidad máxima del sistema solo con discos 


| E8ds_v4 | 12 | 384 TiB 


| E32ds_v4 | 28 | 896 TiB 


| E48ds_v4 | 28 | 896 TiB 


| E80ids_v4 | 28 | 896 TiB 


| E8ds_v5 | 12 | 384 TiB 


| E20ds_v5 | 28 | 896 TiB 


| E32ds_v5 | 28 | 896 TiB 


| E48ds_v5 | 28 | 896 TiB 


| E64ds_v5 | 28 | 896 TiB 


| L16s_v3 | 28 | 896 TiB 


| L32s_v3 | 28 | 896 TiB 


| L48s_v3 | 28 | 896 TiB 


| L64s_v3 | 28 | 896 TiB 
|===


=== Límites para diferentes modos de implementación de licencias basadas en nodos

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que utilizan licencias basadas en nodos. El licenciamiento basado en nodos es el modelo de la generación anterior que le permite licenciar Cloud Volumes ONTAP por nodo. Las licencias basadas en nodos todavía están disponibles para los clientes existentes.

Puede comprar varias licencias basadas en nodos para un sistema de par HA o un solo nodo BYOL de Cloud Volumes ONTAP para asignar más de 368 TiB de capacidad, hasta el límite máximo de capacidad del sistema probado y compatible de 2 PiB. Tenga en cuenta que los límites de disco pueden impedirle alcanzar el límite de capacidad utilizando solo discos. Puedes superar el límite del disco mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] . https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Descubra cómo agregar licencias de sistema adicionales a Cloud Volumes ONTAP"^] . Cloud Volumes ONTAP admite hasta la capacidad máxima probada y compatible del sistema de 2 PiB, y superar el límite de 2 PiB da como resultado una configuración del sistema no compatible.



==== Nodo único

El nodo único tiene dos opciones de licencia basadas en nodos: PAYGO Premium y BYOL.

.Nodo único con PAYGO Premium
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamaño de VM | Máximo de discos de datos por nodo | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y niveles de datos 


| DS5_v2 | 61 | 368 TiB | 368 TiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB 


| E32s_v3 | 29 | 368 TiB | 368 TiB 


| E48s_v3 | 29 | 368 TiB | 368 TiB 


| E64is_v3 | 29 | 368 TiB | 368 TiB 


| E32ds_v4 | 29 | 368 TiB | 368 TiB 


| E48ds_v4 | 29 | 368 TiB | 368 TiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB 


| E20ds_v5 | 29 | 896 TiB | 2 PiB 


| E32ds_v5 | 29 | 896 TiB | 2 PiB 


| E48ds_v5 | 29 | 896 TiB | 2 PiB 


| E64ds_v5 | 29 | 896 TiB | 2 PiB 
|===
====
.Nodo único con BYOL
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamaño de VM | Máximo de discos de datos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con múltiples licencias 


2+|  | *Discos solos* | *Discos + niveles de datos* | *Discos solos* | *Discos + niveles de datos* 


| DS4_v2 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS5_v2 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS13_v2 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| L8s_v2 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E4s_v3 | 5 | 160 TiB | 368 TiB | 160 TiB | 2 PiB 


| E8s_v3 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E32s_v3 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E48s_v3 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E64is_v3 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E4ds_v4 | 5 | 160 TiB | 368 TiB | 160 TiB | 2 PiB 


| E8ds_v4 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E32ds_v4 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E48ds_v4 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E4ds_v5 | 5 | 160 TiB | 368 TiB | 160 TiB | 2 PiB 


| E8ds_v5 | 13 | 368 TiB | 368 TiB | 416 TiB | 2 PiB 


| E20ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E32ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E48ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 


| E64ds_v5 | 29 | 368 TiB | 368 TiB | 896 TiB | 2 PiB 
|===
====


==== Pares HA

Los pares de alta disponibilidad tienen dos tipos de configuración: blob de página y zona de disponibilidad múltiple.  Cada configuración tiene dos opciones de licencia basadas en nodos: PAYGO Premium y BYOL.

.PAYGO Premium: pares de alta disponibilidad en una única zona de disponibilidad con blobs de página
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y niveles de datos 


| DS5_v2 | 61 | 368 TiB | 368 TiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB 


| E8s_v3 | 13 | 104 TiB | 368 TiB 


| E48s_v3 | 29 | 232 TiB | 368 TiB 


| E32ds_v4 | 29 | 232 TiB | 368 TiB 


| E48ds_v4 | 29 | 232 TiB | 368 TiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB 
|===
====
.PAYGO Premium: pares de alta disponibilidad en una configuración de zonas de disponibilidad múltiple con discos administrados compartidos
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y niveles de datos 


| E32ds_v4 | 28 | 368 TiB | 368 TiB 


| E48ds_v4 | 28 | 368 TiB | 368 TiB 


| E80ids_v4 | 28 | 368 TiB | 368 TiB 


| E20ds_v5 | 28 | 896 TiB | 2 PiB 


| E32ds_v5 | 28 | 896 TiB | 2 PiB 


| E48ds_v5 | 28 | 896 TiB | 2 PiB 


| E64ds_v5 | 28 | 896 TiB | 2 PiB 
|===
====
.BYOL: pares de alta disponibilidad en una única zona de disponibilidad con blobs de página
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con múltiples licencias 


2+|  | *Discos solos* | *Discos + niveles de datos* | *Discos solos* | *Discos + niveles de datos* 


| DS4_v2 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| DS5_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 


| DS13_v2 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| DS14_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 


| DS15_v2 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 


| E8s_v3 | 13 | 104 TiB | 368 TiB | 104 TiB | 2 PiB 


| E48s_v3 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| E8ds_v4 | 13 | 104 TiB | 368 TiB | 104 TiB | 2 PiB 


| E32ds_v4 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| E48ds_v4 | 29 | 232 TiB | 368 TiB | 232 TiB | 2 PiB 


| E80ids_v4 | 61 | 368 TiB | 368 TiB | 488 TiB | 2 PiB 
|===
====
.BYOL: pares de alta disponibilidad en una configuración de zonas de disponibilidad múltiple con discos administrados compartidos
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Tamaño de VM | Máximo de discos de datos para un par HA 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con múltiples licencias 


2+|  | *Discos solos* | *Discos + niveles de datos* | *Discos solos* | *Discos + niveles de datos* 


| E8ds_v4 | 12 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E32ds_v4 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E48ds_v4 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E80ids_v4 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E8ds_v5 | 12 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E20ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E32ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E48ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 


| E64ds_v5 | 28 | 368 TiB | 368 TiB | 368 TiB | 2 PiB 
|===
====


== Límites de máquinas virtuales de almacenamiento

Algunas configuraciones le permiten crear máquinas virtuales de almacenamiento (SVM) adicionales para Cloud Volumes ONTAP.

Éstos son los límites probados. No se admite la configuración de más máquinas virtuales de almacenamiento.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html["Aprenda a crear máquinas virtuales de almacenamiento adicionales"^] .

[cols="2*"]
|===
| Tipo de licencia | Límite de máquinas virtuales de almacenamiento 


| *Freemium*  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *PAYGO o BYOL basado en capacidad* ^3^  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *BYOL basado en nodos* ^4^  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *PAYGO basado en nodos*  a| 
* 1 máquina virtual de almacenamiento para servir datos
* 1 máquina virtual de almacenamiento para recuperación ante desastres


|===
. Estas 24 máquinas virtuales de almacenamiento pueden servir datos o configurarse para recuperación ante desastres (DR).
. Cada máquina virtual de almacenamiento puede tener hasta tres LIF, donde dos son LIF de datos y uno es un LIF de administración de SVM.
. En el caso de las licencias basadas en capacidad, no hay costos de licencia adicionales para máquinas virtuales de almacenamiento adicionales, pero hay un cargo de capacidad mínima de 4 TiB por máquina virtual de almacenamiento.  Por ejemplo, si crea dos máquinas virtuales de almacenamiento y cada una tiene 2 TiB de capacidad aprovisionada, se le cobrará un total de 8 TiB.
. Para BYOL basado en nodos, se requiere una licencia complementaria para cada máquina virtual de almacenamiento _de servicio de datos_ adicional más allá de la primera máquina virtual de almacenamiento que viene con Cloud Volumes ONTAP de manera predeterminada. Comuníquese con su equipo de cuentas para obtener una licencia complementaria de máquina virtual de almacenamiento.
+
Las máquinas virtuales de almacenamiento para recuperación ante desastres (DR) no necesitan una licencia complementaria, pero cuentan para el límite de máquinas virtuales de almacenamiento. Por ejemplo, si tiene 12 máquinas virtuales de servicio de datos y 12 máquinas virtuales de almacenamiento de recuperación ante desastres, habrá alcanzado el límite y no podrá crear más.





== Límites de archivos y volúmenes

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


.2+| *Archivos* | Tamaño máximo ^2^ | 128 TB 


| Máximo por volumen | Depende del tamaño del volumen, hasta 2 mil millones 


| * Volúmenes FlexClone * | Profundidad de clonación jerárquica ^1^ | 499 


.3+| * Volúmenes FlexVol * | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo ^3^ | 300 TiB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Copias instantáneas* | Máximo por FlexVol volume | 1.023 
|===
. La profundidad de clonación jerárquica es la profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un solo FlexVol volume.
. A partir de ONTAP 9.12.1P2, el límite es 128 TB.  En ONTAP 9.11.1 y versiones anteriores, el límite es de 16 TB.
. La creación de FlexVol volume hasta un tamaño máximo de 300 TiB es compatible con las siguientes herramientas y versiones mínimas:
+
** Administrador del sistema y la CLI de ONTAP a partir de Cloud Volumes ONTAP 9.12.1 P2 y 9.13.0 P2
** BlueXP a partir de Cloud Volumes ONTAP 9.13.1






== Límites de almacenamiento iSCSI

[cols="3*"]
|===
| almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamaño máximo | 16 TiB 


| Máximo por volumen | 512 


| *igroups* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *Sesiones iSCSI* | Máximo por nodo | 1.024 


.2+| *LIFs* | Máximo por puerto | 32 


| Máximo por conjunto de puertos | 32 


| *Conjuntos de puertos* | Máximo por nodo | 256 
|===