---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.16.1 incluye una nueva mejora. 
---
= Novedades de Cloud Volumes ONTAP 9.16.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.16.1 incluye nuevas mejoras.

Las últimas versiones de la NetApp Console también introducen nuevas funciones de Cloud Volumes ONTAP . Para obtener más información, consulte las novedades en https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^] gestionado en la consola.



[[9-16-1-p12-14-may-2026]]
== 9.16.1 P12 (14 de mayo de 2026)

El parche Cloud Volumes ONTAP 9.16.1 P12 ya está disponible para actualización para todos los proveedores de cloud. La consola te pedirá que actualices tus sistemas existentes a esta versión del parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P12["Ver la lista de errores corregidos en el parche P12"^] (NetApp se requiere inicio de sesión en Support Site).



[[9-16-1-p11-17-february-2026]]
== 9.16.1 P11 (17 de febrero de 2026)

El parche Cloud Volumes ONTAP 9.16.1 P11 ya está disponible para actualización para todos los proveedores de cloud. La consola te pedirá que actualices tus sistemas existentes a esta versión del parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P11["Ver la lista de errores corregidos en el parche P11"^] (NetApp se requiere inicio de sesión en Support Site).



[[9-16-1-p10-22-december-2025]]
== 9.16.1 P10 (22 de diciembre de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P10 ya está disponible para la actualización para todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P10["Ver la lista de errores corregidos en el parche P10"^](Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p9-04-december-2025]]
== 9.16.1 P9 (04 de diciembre de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P9 ya está disponible para la actualización para todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P9["Ver la lista de errores corregidos en el parche P9"^](Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p8-16-october-2025]]
== 9.16.1 P8 (16 de octubre de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P8 ya está disponible para la actualización en todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P8["Ver la lista de errores corregidos en el parche P8"^](Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p7-09-october-2025]]
== 9.16.1 P7 (9 de octubre de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P7 ya está disponible para la actualización en todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P7["Ver la lista de errores corregidos en el parche P7"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p6-09-october-2025]]
== 9.16.1 P6 (9 de octubre de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P6 ya está disponible para la actualización en todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P6["Ver la lista de errores corregidos en el parche P6"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p5-28-july-2025]]
== 9.16.1 P5 (28 de julio de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P5 ya está disponible para la actualización en todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P5["Ver la lista de errores corregidos en el parche P5"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p4-08-july-2025]]
== 9.16.1 P4 (8 de julio de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P4 ya está disponible para la actualización en todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P4["Ver la lista de errores corregidos en el parche P4"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p3-29-may-2025]]
== 9.16.1 P3 (29 de mayo de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P3 ya está disponible para la actualización en todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3["Ver la lista de errores corregidos en el parche P3"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p2-17-april-2025]]
== 9.16.1 P2 (17 de abril de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P2 ya está disponible para la actualización para todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2["Ver la lista de errores corregidos en el parche P2"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-p1-17-april-2025]]
== 9.16.1 P1 (17 de abril de 2025)

El parche Cloud Volumes ONTAP 9.16.1 P1 ya está disponible para la actualización para todos los proveedores de nube. La consola le pedirá que actualice sus sistemas existentes a esta versión de parche.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1["Ver la lista de errores corregidos en el parche P1"^] (Se requiere iniciar sesión en el sitio de soporte de NetApp ).



[[9-16-1-ga-06-march-2025]]
== 9.16.1 GA (6 de marzo de 2025)

La versión de disponibilidad general 9.16.1 de Cloud Volumes ONTAP ya está disponible para su implementación y actualización en AWS, Azure y Google Cloud.



[[upgrade-notes]]
== Notas de actualización

Lea estas notas para obtener más información sobre cómo actualizar a esta versión.



[[how-to-upgrade]]
=== Cómo actualizar

Las actualizaciones de Cloud Volumes ONTAP deben completarse desde la consola. No debe actualizar Cloud Volumes ONTAP mediante el Administrador del sistema o la CLI. Hacerlo puede afectar la estabilidad del sistema.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Aprende cómo actualizar cuando la consola te notifique."^].



[[supported-upgrade-path]]
=== Ruta de actualización compatible

Puedes actualizar a Cloud Volumes ONTAP 9.16.1 desde la versión 9.15.1 en AWS, Azure y Google Cloud.  La consola le solicitará que actualice los sistemas Cloud Volumes ONTAP elegibles a esta versión.



[[downtime]]
=== Falta del tiempo

* La actualización de un sistema de un solo nodo deja el sistema fuera de línea durante hasta 25 minutos, durante los cuales se interrumpe la E/S.
* La actualización de un par HA no produce interrupciones y la E/S no se interrumpe.  Durante este proceso de actualización sin interrupciones, cada nodo se actualiza simultáneamente para continuar brindando servicios de E/S a los clientes.

