---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: Estas limitaciones conocidas son específicas de Cloud Volumes ONTAP en Amazon Web Services. 
---
= Limitaciones conocidas de Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las siguientes limitaciones conocidas son específicas de Cloud Volumes ONTAP en Amazon Web Services.  Asegúrese de revisar tambiénlink:reference-limitations.html["Limitaciones de Cloud Volumes ONTAP en todos los proveedores de nube"] .



== Limitaciones de AWS Outpost

Si tiene un AWS Outpost, puede implementar Cloud Volumes ONTAP en ese Outpost seleccionando la VPC de Outpost en el asistente de entorno de trabajo.  La experiencia es la misma que la de cualquier otra VPC que resida en AWS.  Tenga en cuenta que primero deberá implementar un conector en su AWS Outpost.

Hay algunas limitaciones que conviene señalar:

* En este momento, solo se admiten sistemas Cloud Volumes ONTAP de un solo nodo
* Las instancias EC2 que puede usar con Cloud Volumes ONTAP están limitadas a lo que está disponible en su puesto avanzado
* En este momento solo se admiten SSD de propósito general (gp2)




== Limitaciones de la caché Flash

Los tipos de instancias C5D y R5D incluyen almacenamiento NVMe local, que Cloud Volumes ONTAP utiliza como _Flash Cache_.  Tenga en cuenta las siguientes limitaciones:

* La compresión debe estar deshabilitada en todos los volúmenes para aprovechar las mejoras de rendimiento de Flash Cache hasta Cloud Volumes ONTAP 9.12.0.  Cuando implementa o actualiza a Cloud Volumes ONTAP 9.12.1, no necesita deshabilitar la compresión.
+
Puede elegir no usar eficiencia de almacenamiento al crear un volumen desde BlueXP, o puede crear un volumen y luego http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["deshabilitar la compresión de datos mediante la CLI"^] .

* El recalentamiento de la caché después de un reinicio no es compatible con Cloud Volumes ONTAP.




== Falsas alarmas reportadas por Amazon CloudWatch

Cloud Volumes ONTAP no libera CPU cuando está inactivo, por lo que https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] puede informar una advertencia de alto uso de CPU para la instancia EC2 porque detecta un uso del 100 %.  Puedes ignorar esta alarma.  El comando de estadísticas de ONTAP muestra el uso real de las CPU.



== Los pares de Cloud Volumes ONTAP HA no admiten la devolución inmediata de almacenamiento

Después de que un nodo se reinicia, el socio debe sincronizar los datos antes de poder devolver el almacenamiento.  El tiempo que lleva resincronizar los datos depende de la cantidad de datos escritos por los clientes mientras el nodo estaba inactivo y de la velocidad de escritura de datos durante el tiempo de recuperación.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["Descubra cómo funciona el almacenamiento en un par de Cloud Volumes ONTAP HA que se ejecuta en AWS"^] .
