---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en Google Cloud para proporcionar operaciones confiables.  Para obtener el mejor rendimiento, no configure su sistema con los valores máximos. 
---
= Límites de almacenamiento para Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones confiables.  Para obtener el mejor rendimiento, no configure su sistema con los valores máximos.



== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema para un sistema Cloud Volumes ONTAP está determinada por su licencia. La capacidad máxima del sistema incluye almacenamiento basado en disco más almacenamiento de objetos utilizado para la clasificación de datos.

NetApp no admite exceder el límite de capacidad del sistema. Si alcanza el límite de capacidad autorizado, BlueXP muestra un mensaje de acción requerida y ya no le permite agregar discos adicionales.

Para algunas configuraciones, los límites de disco impiden que se alcance el límite de capacidad utilizando solo discos.  Puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] .  Consulte los límites de disco a continuación para obtener más detalles.

.Límite de capacidad para licencias basadas en capacidad
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos. La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube. Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles. Consulte la  https://cloud.google.com/storage/docs/buckets["Documentación de Google Cloud"^] Para más información.

Límites de capacidad para otros tipos de licencias::


[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GB 


| PAYGO Explorar | 2 TB (la clasificación de datos no es compatible con Explore) 


| Estándar PAYGO | 10 TB 


| Prima de pago por uso | 368 TB 


| Licencia basada en nodos | 2 PiB (requiere múltiples licencias) 
|===
.Para un par HA, ¿el límite de capacidad con licencia es por nodo o para todo el par HA?
El límite de capacidad es para todo el par HA. No es por nodo. Por ejemplo, si utilizas la licencia Premium, podrás tener hasta 368 TB de capacidad entre ambos nodos.

.Para un par HA, ¿los datos reflejados se tienen en cuenta para el límite de capacidad con licencia?
No, no lo es. Los datos de un par HA se reflejan de forma sincrónica entre los nodos para que estén disponibles en caso de falla en Google Cloud. Por ejemplo, si compra un disco de 8 TB en el nodo A, BlueXP también asigna un disco de 8 TB en el nodo B que se utiliza para datos reflejados. Si bien se configuran 16 TB de capacidad, solo 8 TB cuentan para el límite de la licencia.



== Límites agregados

Cloud Volumes ONTAP agrupa los discos de Google Cloud Platform en _agregados_.  Los agregados proporcionan almacenamiento a los volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados de datos ^1^  a| 
* 99 para un solo nodo
* 64 para un par HA completo




| Tamaño máximo del agregado | 256 TB de capacidad bruta ^2^ 


| Discos por agregado | 1-6 ^3^ 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. El número máximo de agregados de datos no incluye el agregado raíz.
. Los discos que componen el agregado determinan el límite de capacidad del agregado. Este límite no incluye el almacenamiento de objetos utilizado para la clasificación de datos.
. Todos los discos de un agregado deben tener el mismo tamaño.




== Límites de disco y niveles

La siguiente tabla muestra la capacidad máxima del sistema con solo discos y con discos y niveles de datos fríos en el almacenamiento de objetos.  Los límites del disco son específicos de los discos que contienen datos del usuario.  Los límites no incluyen el disco de arranque, el disco raíz o la NVRAM.

[cols="60,40"]
|===
| Parámetro | Límite 


| Máximo de discos de datos  a| 
* 124 para sistemas de nodo único
* 123 por nodo para pares HA




| Tamaño máximo del disco | 64 TB 


| Capacidad máxima del sistema solo con discos | 256 TB ^1^ 


| Capacidad máxima del sistema con discos y niveles de datos fríos en un depósito de Google Cloud Storage | Depende de la licencia.  Consulte los límites de capacidad máxima del sistema más arriba. 
|===
^1^ Este límite está definido por los límites de las máquinas virtuales en Google Cloud Platform.



== Límites de máquinas virtuales de almacenamiento

Algunas configuraciones le permiten crear máquinas virtuales de almacenamiento (SVM) adicionales para Cloud Volumes ONTAP.

Éstos son los límites probados. No se admite la configuración de más máquinas virtuales de almacenamiento.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Aprenda a crear máquinas virtuales de almacenamiento adicionales"^] .

[cols="2*"]
|===
| Tipo de licencia | Límite de máquinas virtuales de almacenamiento 


| *Freemium*  a| 
24 máquinas virtuales de almacenamiento en total ^1^



| *PAYGO o BYOL basado en capacidad* ^2^  a| 
24 máquinas virtuales de almacenamiento en total ^1^



| *BYOL basado en nodos* ^3^  a| 
24 máquinas virtuales de almacenamiento en total ^1^



| *PAYGO basado en nodos*  a| 
* 1 máquina virtual de almacenamiento para servir datos
* 1 máquina virtual de almacenamiento para recuperación ante desastres


|===
. Estas 24 máquinas virtuales de almacenamiento pueden servir datos o configurarse para recuperación ante desastres (DR).
. En el caso de las licencias basadas en capacidad, no hay costos de licencia adicionales para máquinas virtuales de almacenamiento adicionales, pero hay un cargo de capacidad mínima de 4 TiB por máquina virtual de almacenamiento.  Por ejemplo, si crea dos máquinas virtuales de almacenamiento y cada una tiene 2 TiB de capacidad aprovisionada, se le cobrará un total de 8 TiB.
. Para BYOL basado en nodos, se requiere una licencia complementaria para cada máquina virtual de almacenamiento _de servicio de datos_ adicional más allá de la primera máquina virtual de almacenamiento que viene con Cloud Volumes ONTAP de manera predeterminada. Comuníquese con su equipo de cuentas para obtener una licencia complementaria de máquina virtual de almacenamiento.
+
Las máquinas virtuales de almacenamiento que configure para recuperación ante desastres (DR) no requieren una licencia complementaria (son gratuitas), pero sí cuentan para el límite de máquinas virtuales de almacenamiento.  Por ejemplo, si tiene 12 máquinas virtuales de almacenamiento que brindan servicio de datos y 12 máquinas virtuales de almacenamiento configuradas para recuperación ante desastres, entonces habrá alcanzado el límite y no podrá crear máquinas virtuales de almacenamiento adicionales.





== Límites de almacenamiento lógico

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


.2+| *Archivos* | Tamaño máximo ^2^ | 128 TB 


| Máximo por volumen | Depende del tamaño del volumen, hasta 2 mil millones 


| * Volúmenes FlexClone * | Profundidad de clonación jerárquica ^12^ | 499 


.3+| * Volúmenes FlexVol * | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo ^3^ | 300 TiB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Copias instantáneas* | Máximo por FlexVol volume | 1.023 
|===
. La profundidad de clonación jerárquica es la profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un solo FlexVol volume.
. A partir de ONTAP 9.12.1P2, el límite es 128 TB.  En ONTAP 9.11.1 y versiones anteriores, el límite es de 16 TB.
. La creación de FlexVol volume hasta un tamaño máximo de 300 TiB es compatible con las siguientes herramientas y versiones mínimas:
+
** Administrador del sistema y la CLI de ONTAP a partir de Cloud Volumes ONTAP 9.12.1 P2 y 9.13.0 P2
** BlueXP a partir de Cloud Volumes ONTAP 9.13.1






== Límites de almacenamiento iSCSI

[cols="3*"]
|===
| almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamaño máximo | 16 TB 


| Máximo por volumen | 512 


| *igroups* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *Sesiones iSCSI* | Máximo por nodo | 1.024 


.2+| *LIFs* | Máximo por puerto | 1 


| Máximo por conjunto de puertos | 32 


| *Conjuntos de puertos* | Máximo por nodo | 256 
|===


== Los pares de Cloud Volumes ONTAP HA no admiten la devolución inmediata de almacenamiento

Después de que un nodo se reinicia, el socio debe sincronizar los datos antes de poder devolver el almacenamiento.  El tiempo que lleva resincronizar los datos depende de la cantidad de datos escritos por los clientes mientras el nodo estaba inactivo y de la velocidad de escritura de datos durante el tiempo de recuperación.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Descubra cómo funciona el almacenamiento en un par de Cloud Volumes ONTAP HA que se ejecuta en Google Cloud"^] .
