---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en AWS para proporcionar operaciones confiables.  Para obtener el mejor rendimiento, no configure su sistema con los valores máximos. 
---
= Límites de almacenamiento para Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones confiables.  Para obtener el mejor rendimiento, no configure su sistema con los valores máximos.



== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema incluye almacenamiento basado en disco más almacenamiento de objetos utilizado para la clasificación de datos.

NetApp no admite exceder el límite de capacidad del sistema. Si alcanza el límite de capacidad autorizado, BlueXP muestra un mensaje de acción requerida y ya no le permite agregar discos adicionales.

Para algunas configuraciones, los límites de disco impiden que se alcance el límite de capacidad utilizando solo discos.  En esos casos, puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] .  Consulte la capacidad y los límites de disco a continuación para obtener más detalles.

.Límite de capacidad para licencias basadas en capacidad
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos. La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube. Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles. Consulte la  https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentación de AWS"^] Para más información.

Límites de capacidad para otros tipos de licencias::


[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explorar | 2 TiB (la estratificación de datos no es compatible con Explore) 


| Estándar PAYGO | 10 TiB 


| Prima de pago por uso | 368 TiB 


| Licencia basada en nodos | 2 PiB (requiere múltiples licencias) 
|===
.Para HA, ¿el límite de capacidad de la licencia es por nodo o para todo el par de HA?
El límite de capacidad es para todo el par HA. No es por nodo. Por ejemplo, la licencia Premium permite hasta 368 TiB en ambos nodos.

.Para un sistema HA en AWS, ¿los datos reflejados cuentan para el límite de capacidad?
No, no lo es. Los datos de un par de AWS HA se reflejan de forma sincrónica entre los nodos para que estén disponibles en caso de falla.  Por ejemplo, si compra un disco de 8 TiB en el nodo A, BlueXP también asigna un disco de 8 TiB en el nodo B que se utiliza para datos reflejados.  Si bien se aprovisionaron 16 TiB de capacidad, solo 8 TiB cuentan para el límite de la licencia.



== Límites agregados

Cloud Volumes ONTAP utiliza volúmenes EBS como discos y los agrupa en _agregados_.  Los agregados proporcionan almacenamiento a los volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados | Nodo único: Igual que el límite de disco Pares de alta disponibilidad: 18 en un nodo ^1^ 


| Tamaño máximo del agregado ^2^  a| 
* 96 TiB de capacidad bruta
* 128 TiB de capacidad bruta con volúmenes elásticos ^3^




| Discos por agregado ^4^  a| 
* 1-6
* 1-8 con volúmenes elásticos ^3^




| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. No se pueden crear 18 agregados en ambos nodos de un par de alta disponibilidad porque eso excedería el límite del disco de datos.
. El tamaño agregado máximo depende de sus discos y no incluye el almacenamiento de objetos que utiliza para la clasificación de datos.
. Si tiene una configuración que admite la función Volumen elástico de Amazon EBS, un agregado puede contener hasta 8 discos, lo que proporciona hasta 128 TiB de capacidad. De forma predeterminada, los sistemas Cloud Volumes ONTAP 9.11.0 y posteriores tienen Amazon EBS Elastic Volumes habilitado cuando usa discos gp3 o io1. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Obtenga más información sobre la compatibilidad con Elastic Volumes"^]
. Todos los discos de un agregado deben tener el mismo tamaño.




== Límites de disco y niveles por instancia EC2

Los límites de capacidad son diferentes según la familia de tipos de instancias EC2 que utilice y si está usando un sistema de nodo único o un par de alta disponibilidad.

Las siguientes notas proporcionan detalles sobre los números que verá en las tablas a continuación:

* Los límites del disco son específicos de los discos que contienen datos del usuario.
+
Los límites no incluyen el disco de arranque ni el disco raíz.

* Se indica una capacidad máxima del sistema cuando se utilizan solos discos y cuando se utilizan discos y niveles de datos fríos en el almacenamiento de objetos.
* Cloud Volumes ONTAP utiliza volúmenes EBS como discos, con un tamaño de disco máximo de 16 TiB.




=== Límites para diferentes modos de implementación de licencias basadas en capacidad

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que utilizan un paquete de licencias basado en capacidad. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Obtenga más información sobre las opciones de licencia de Cloud Volumes ONTAP"^]


NOTE: Para conocer la capacidad máxima del sistema y los límites de capacidad de niveles de datos para configuraciones de nodo único y alta disponibilidad, consulte<<cap-license-aws>> .



==== Nodo único

[cols="18,18,32,width=100%,options="]
|===


| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos 


| Instancias c5, m5 y r5 | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304 TiB 
|===
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== Pares HA

[cols="18,18,32,width=100%,options="]
|===


| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos 


| Instancias c5, m5 y r5 | 18 | 288 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^1^ | 256 TiB 
|===
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




=== Límites para diferentes modos de implementación de licencias basadas en nodos

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que usan licencias basadas en nodos, que es el modelo de licencias de la generación anterior que le permitía obtener licencias de Cloud Volumes ONTAP por nodo. Las licencias basadas en nodos todavía están disponibles para los clientes existentes.

Puede comprar varias licencias basadas en nodos para un sistema de par HA o un solo nodo BYOL de Cloud Volumes ONTAP para asignar más de 368 TiB de capacidad, hasta el límite máximo de capacidad del sistema probado y compatible de 2 PiB. Tenga en cuenta que los límites de disco pueden impedirle alcanzar el límite de capacidad utilizando solo discos. Puedes superar el límite del disco mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] . https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Descubra cómo agregar licencias de sistema adicionales a Cloud Volumes ONTAP"^] . Si bien Cloud Volumes ONTAP admite hasta la capacidad máxima del sistema probada y compatible de 2 PiB, superar el límite de 2 PiB da como resultado una configuración del sistema no compatible.

Las regiones AWS Secret Cloud y Top Secret Cloud admiten compras de licencias basadas en múltiples nodos a partir de Cloud Volumes ONTAP 9.12.1.



==== Nodo único con PAYGO Premium

[cols="18,18,32,32"]
|===
| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y niveles de datos 


| Instancias c5, m5 y r5 | 21 ^1^ | 336 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB 
|===
. 21 discos de datos es el límite para las _nuevas_ implementaciones de Cloud Volumes ONTAP.  Si actualiza un sistema creado con la versión 9.7 o anterior, el sistema seguirá admitiendo 22 discos.  En los sistemas nuevos que usan estos tipos de instancias se admite un disco de datos menos debido a la incorporación de un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== Nodo único con BYOL

[cols="18,18,16,16,16,16"]
|===
| Instancia | Máximo de discos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con múltiples licencias 


2+|  | *Discos solos* | *Discos + niveles de datos* | *Discos solos* | *Discos + niveles de datos* 


| Instancias c5, m5 y r5 | 21 ^1^ | 336 TiB | 368 TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB | 304 TiB | 2 PiB 
|===
. 21 discos de datos es el límite para las _nuevas_ implementaciones de Cloud Volumes ONTAP.  Si actualiza un sistema creado con la versión 9.7 o anterior, el sistema seguirá admitiendo 22 discos.  En los sistemas nuevos que usan estos tipos de instancias se admite un disco de datos menos debido a la incorporación de un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== HA se empareja con PAYGO Premium

[cols="18,18,32,32"]
|===
| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y niveles de datos 


| Instancias c5, m5 y r5 | 18 ^1^ | 288 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB 
|===
. 18 discos de datos es el límite para las _nuevas_ implementaciones de Cloud Volumes ONTAP.  Si actualiza un sistema creado con la versión 9.7 o anterior, el sistema seguirá admitiendo 19 discos.  En los sistemas nuevos que usan estos tipos de instancias se admite un disco de datos menos debido a la incorporación de un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== HA se empareja con BYOL

[cols="18,18,16,16,16,16"]
|===
| Instancia | Máximo de discos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con múltiples licencias 


2+|  | *Discos solos* | *Discos + niveles de datos* | *Discos solos* | *Discos + niveles de datos* 


| Instancias c5, m5 y r5 | 18 ^1^ | 288 TiB | 368 TiB | 288 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB | 256 TiB | 2 PiB 
|===
. 18 discos de datos es el límite para las _nuevas_ implementaciones de Cloud Volumes ONTAP.  Si actualiza un sistema creado con la versión 9.7 o anterior, el sistema seguirá admitiendo 19 discos.  En los sistemas nuevos que usan estos tipos de instancias se admite un disco de datos menos debido a la incorporación de un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




== Límites de máquinas virtuales de almacenamiento

Algunas configuraciones le permiten crear máquinas virtuales de almacenamiento (SVM) adicionales para Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["Aprenda a crear máquinas virtuales de almacenamiento adicionales"^] .

[cols="40,60"]
|===
| Tipo de licencia | Límite de máquinas virtuales de almacenamiento 


| *Freemium*  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *PAYGO o BYOL basado en capacidad* ^3^  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *PAYGO basado en nodos*  a| 
* 1 máquina virtual de almacenamiento para servir datos
* 1 máquina virtual de almacenamiento para recuperación ante desastres




| *BYOL basado en nodos* ^4^  a| 
* 24 máquinas virtuales de almacenamiento en total ^1,2^


|===
. El límite puede ser menor, dependiendo del tipo de instancia EC2 que utilice.  Los límites por instancia se enumeran en la sección siguiente.
. Estas 24 máquinas virtuales de almacenamiento pueden servir datos o configurarse para recuperación ante desastres (DR).
. En el caso de las licencias basadas en capacidad, no hay costos de licencia adicionales para máquinas virtuales de almacenamiento adicionales, pero hay un cargo de capacidad mínima de 4 TiB por máquina virtual de almacenamiento.  Por ejemplo, si crea dos máquinas virtuales de almacenamiento y cada una tiene 2 TiB de capacidad aprovisionada, se le cobrará un total de 8 TiB.
. Para BYOL basado en nodos, se requiere una licencia complementaria para cada máquina virtual de almacenamiento _de servicio de datos_ adicional más allá de la primera máquina virtual de almacenamiento que viene con Cloud Volumes ONTAP de manera predeterminada. Comuníquese con su equipo de cuentas para obtener una licencia complementaria de máquina virtual de almacenamiento.
+
Las máquinas virtuales de almacenamiento que configure para recuperación ante desastres (DR) no requieren una licencia complementaria (son gratuitas), pero sí cuentan para el límite de máquinas virtuales de almacenamiento.  Por ejemplo, si tiene 12 máquinas virtuales de almacenamiento que brindan servicio de datos y 12 máquinas virtuales de almacenamiento configuradas para recuperación ante desastres, entonces habrá alcanzado el límite y no podrá crear máquinas virtuales de almacenamiento adicionales.





=== Límite de máquinas virtuales de almacenamiento por tipo de instancia EC2

Cuando crea una máquina virtual de almacenamiento adicional, debe asignar direcciones IP privadas al puerto e0a.  La siguiente tabla identifica la cantidad máxima de IP privadas por interfaz, así como la cantidad de direcciones IP que están disponibles en el puerto e0a después de implementar Cloud Volumes ONTAP .  La cantidad de direcciones IP disponibles afecta directamente la cantidad máxima de máquinas virtuales de almacenamiento para esa configuración.

Las instancias que se enumeran a continuación corresponden a las familias de instancias c5, m5 y r5.

[cols="6*"]
|===
| Configuración | Tipo de instancia | Máximo de IP privadas por interfaz | IP restantes después de la implementación ^1^ | Máximo almacenamiento de máquinas virtuales sin un LIF de administración ^2,3^ | Máximo almacenamiento de máquinas virtuales con un LIF de administración ^2,3^ 


.9+| *Nodo único* | *.xgrande | 15 | 9 | 10 | 5 


| *.2xgrande | 15 | 9 | 10 | 5 


| *.4xgrande | 30 | 24 | 24 | 12 


| *.8xgrande | 30 | 24 | 24 | 12 


| *.9xgrande | 30 | 24 | 24 | 12 


| *.12xgrande | 30 | 24 | 24 | 12 


| *.16xgrande | 50 | 44 | 24 | 12 


| *.18xgrande | 50 | 44 | 24 | 12 


| *.24xgrande | 50 | 44 | 24 | 12 


.9+| *Par HA en una sola zona de disponibilidad* | *.xgrande | 15 | 10 | 11 | 5 


| *.2xgrande | 15 | 10 | 11 | 5 


| *.4xgrande | 30 | 25 | 24 | 12 


| *.8xgrande | 30 | 25 | 24 | 12 


| *.9xgrande | 30 | 25 | 24 | 12 


| *.12xgrande | 30 | 25 | 24 | 12 


| *.16xgrande | 50 | 45 | 24 | 12 


| *.18xgrande | 50 | 45 | 24 | 12 


| *.24xgrande | 50 | 44 | 24 | 12 


.9+| *Par HA en múltiples AZ* | *.xgrande | 15 | 12 | 13 | 13 


| *.2xgrande | 15 | 12 | 13 | 13 


| *.4xgrande | 30 | 27 | 24 | 24 


| *.8xgrande | 30 | 27 | 24 | 24 


| *.9xgrande | 30 | 27 | 24 | 24 


| *.12xgrande | 30 | 27 | 24 | 24 


| *.16xgrande | 50 | 47 | 24 | 24 


| *.18xgrande | 50 | 47 | 24 | 24 


| *.24xgrande | 50 | 44 | 24 | 12 
|===
. Este número indica cuántas direcciones IP privadas _restantes_ están disponibles en el puerto e0a después de implementar y configurar Cloud Volumes ONTAP .  Por ejemplo, un sistema *.2xlarge admite un máximo de 15 direcciones IP por interfaz de red.  Cuando se implementa un par HA en una sola AZ, se asignan 5 direcciones IP privadas al puerto e0a.  Como resultado, un par HA que utiliza un tipo de instancia *.2xlarge tiene 10 direcciones IP privadas restantes para máquinas virtuales de almacenamiento adicionales.
. El número que aparece en estas columnas incluye la VM de almacenamiento inicial que BlueXP crea de manera predeterminada.  Por ejemplo, si en esta columna aparece 24, significa que puede crear 23 máquinas virtuales de almacenamiento adicionales para un total de 24.
. Un LIF de administración para la VM de almacenamiento es opcional.  Un LIF de administración proporciona una conexión a herramientas de administración como SnapCenter.
+
Debido a que requiere una dirección IP privada, limitará la cantidad de máquinas virtuales de almacenamiento adicionales que puede crear.  La única excepción es un par HA en múltiples AZ.  En ese caso, la dirección IP del LIF de administración es una dirección IP _flotante_, por lo que no cuenta para el límite de IP _privada_.





== Límites de archivos y volúmenes

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


.2+| *Archivos* | Tamaño máximo ^2^ | 128 TB 


| Máximo por volumen | Depende del tamaño del volumen, hasta 2 mil millones 


| * Volúmenes FlexClone * | Profundidad de clonación jerárquica ^1^ | 499 


.3+| * Volúmenes FlexVol * | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo ^3^ | 300 TiB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Copias instantáneas* | Máximo por FlexVol volume | 1.023 
|===
. La profundidad de clonación jerárquica es la profundidad máxima de una jerarquía anidada de volúmenes FlexClone que se pueden crear a partir de un solo FlexVol volume.
. A partir de ONTAP 9.12.1P2, el límite es 128 TB.  En ONTAP 9.11.1 y versiones anteriores, el límite es de 16 TB.
. La creación de FlexVol volume hasta un tamaño máximo de 300 TiB es compatible con las siguientes herramientas y versiones mínimas:
+
** Administrador del sistema y la CLI de ONTAP a partir de Cloud Volumes ONTAP 9.12.1 P2 y 9.13.0 P2
** BlueXP a partir de Cloud Volumes ONTAP 9.13.1






== Límites de almacenamiento iSCSI

[cols="3*"]
|===
| almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamaño máximo | 16 TiB 


| Máximo por volumen | 512 


| *igroups* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *Sesiones iSCSI* | Máximo por nodo | 1.024 


.2+| *LIFs* | Máximo por puerto | 32 


| Máximo por conjunto de puertos | 32 


| *Conjuntos de puertos* | Máximo por nodo | 256 
|===