---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Se admiten varias configuraciones de Cloud Volumes ONTAP en Google Cloud. 
---
= Configuraciones compatibles con Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se admiten varias configuraciones de Cloud Volumes ONTAP en Google Cloud.



== Configuraciones admitidas por licencia

Cloud Volumes ONTAP está disponible en Google Cloud como un sistema de nodo único y como un par de nodos de alta disponibilidad (HA) para tolerancia a fallas y operaciones sin interrupciones.

No se admite la actualización de un sistema de un solo nodo a un par de alta disponibilidad.  Si desea cambiar entre un sistema de un solo nodo y un par de alta disponibilidad, deberá implementar un nuevo sistema y replicar los datos del sistema existente al nuevo sistema.

Cloud Volumes ONTAP puede ejecutarse en una instancia de VM reservada o bajo demanda de su proveedor de nube.  No se admiten soluciones que utilizan otros tipos de instancias de VM.

[role="tabbed-block"]
====
.Licencias basadas en capacidad
--
[cols="h,d,d,d"]
|===
|  | Freemium | Optimizado ^4^ | Licencia basada en capacidad (Essentials y Professional) 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 500 GiB  a| 
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos. La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube. Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles.



| Tipos de máquinas compatibles ^1^  a| 
* n1-estándar-8 ^1^
* n1-estándar-32 ^1^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64

 a| 
* n2-estándar-4
* n2-estándar-8

 a| 
* n1-estándar-8 ^1^
* n1-estándar-32 ^1^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64




| Tipos de discos admitidos ^2^ 3+| Discos persistentes equilibrados ^3^, discos persistentes de rendimiento (SSD) ^3^ y discos persistentes estándar (HDD). 
|===
Notas:

. ^1^ Las máquinas de la serie n1 ya no están disponibles para su selección en BlueXP al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud.  Las máquinas de la serie n1 se conservarán y recibirán soporte únicamente en sistemas más antiguos y existentes.  Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9.8.  Le recomendamos que cambie a las máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores.  Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.
+
El tipo de máquina custom-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP .  Si tiene un sistema existente ejecutándose en este tipo de máquina, puede seguir usándolo, pero le recomendamos cambiar al tipo de máquina n2-standard-4.

. ^2^ Los límites de disco pueden impedir que alcance el límite máximo de capacidad del sistema utilizando solo discos.  Puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] .
+
link:reference-limits-gcp.html["Obtenga más información sobre los límites de disco en Google Cloud"] .

. ^3^ El rendimiento de escritura mejorado se habilita cuando se utilizan discos persistentes equilibrados y discos persistentes de rendimiento (SSD).
+
A partir de Cloud Volumes ONTAP 9.13.0, _Flash Cache_, alta velocidad de escritura y una unidad de transmisión máxima (MTU) más alta de 8896 bytes están disponibles para las siguientes instancias de implementación de pares de alta disponibilidad:

+
** n2-estándar-16
** n2-estándar-32
** n2-estándar-48
** n2-estándar-64
+
Puede habilitar _Flash Cache_ y alta velocidad de escritura al implementar un tipo de instancia elegible.  Para habilitar la unidad de transmisión máxima más alta de 8896 bytes, debe elegir VPC-1, VPC-2 o VPC-3 para la implementación.  Una MTU más alta permite un mayor rendimiento de la red.  Para obtener más información sobre cómo lanzar una de estas implementaciones, consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Lanzamiento de un par HA en Google Cloud"] .

+

NOTE: _Flash cache_, el modo de escritura alta y una MTU de 8896 dependen de las funciones y no se pueden deshabilitar individualmente dentro de una instancia configurada.



. ^4^ A partir del 11 de agosto de 2025, la licencia optimizada de Cloud Volumes ONTAP quedará obsoleta y ya no estará disponible para compra ni renovación en el mercado de Google Cloud para suscripciones de pago por uso (PAYGO). Para obtener más información, consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Novedades de Cloud Volumes ONTAP"^] .


--
.Licencias basadas en nodos
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explorar | Estándar PAYGO | Prima de pago por uso | BYOL basado en nodos 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TB ^2^ | 10 TiB | 368 TiB | 368 TiB por licencia 


| Tipos de máquinas compatibles ^3^  a| 
* n2-estándar-4

 a| 
* n1-estándar-8 ^3^
* n2-estándar-8

 a| 
* n1-estándar-32 ^3^
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64

 a| 
* n1-estándar-8 ^3^
* n1-estándar-32 ^3^
* n2-estándar-4
* n2-estándar-8
* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64




| Tipos de discos compatibles 4+| Discos persistentes equilibrados ^4^, discos persistentes de rendimiento (SSD) ^4^ y discos persistentes estándar (HDD). 
|===
Notas:

. ^1^ Los límites de disco pueden impedir que alcance el límite máximo de capacidad del sistema utilizando solo discos.  Puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] .
+
link:reference-limits-gcp.html["Obtenga más información sobre los límites de disco en Google Cloud"] .

. ^2^ La organización de datos en niveles en Google Cloud Storage no es compatible con PAYGO Explore.
. ^3^ Las máquinas de la serie n1 ya no están disponibles para su selección en BlueXP al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud.  Las máquinas de la serie n1 se conservarán y recibirán soporte únicamente en sistemas más antiguos y existentes.  Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9.8.  Le recomendamos que cambie a las máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores.  Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.
+
El tipo de máquina custom-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP .  Si tiene un sistema existente ejecutándose en este tipo de máquina, puede seguir usándolo, pero le recomendamos cambiar al tipo de máquina n2-standard-4.

. ^4^ El rendimiento de escritura mejorado se habilita cuando se utilizan discos persistentes equilibrados y discos persistentes de rendimiento (SSD).


La interfaz de BlueXP muestra un tipo de máquina compatible adicional para Estándar y BYOL: n1-highmem-4.  Sin embargo, este tipo de máquina no está diseñada para entornos de producción.  Lo hemos puesto a disposición únicamente para un entorno de laboratorio específico.

A partir de la versión 9.13.0 del software Cloud Volumes ONTAP , _Flash Cache_, alta velocidad de escritura y una unidad de transmisión máxima (MTU) más alta de 8896 bytes están disponibles para las siguientes instancias de implementación de pares de alta disponibilidad:

* n2-estándar-16
* n2-estándar-32
* n2-estándar-48
* n2-estándar-64


Puede habilitar _Flash Cache_ y alta velocidad de escritura al implementar un tipo de instancia elegible.  Para habilitar la unidad de transmisión máxima más alta de 8896 bytes, debe elegir VPC-1, VPC-2 o VPC-3 para la implementación.  Una MTU más alta permite un mayor rendimiento de la red.  Para obtener más información sobre cómo lanzar una de estas implementaciones, consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Lanzamiento de un par HA en Google Cloud"] .


NOTE: _Flash cache_, el modo de escritura alta y una MTU de 8896 dependen de las funciones y no se pueden deshabilitar individualmente dentro de una instancia configurada.

--
====
Para obtener más información sobre tipos de máquinas específicas, consulte la documentación de Google Cloud:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["Tipos de máquinas de uso general de la serie n1"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Tipos de máquinas de uso general de la serie N2"^]




== Tamaños de disco admitidos

En Google Cloud, un agregado puede contener hasta 6 discos, todos del mismo tipo y tamaño.  Se admiten los siguientes tamaños de disco:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== Regiones compatibles

Para obtener soporte regional de Google Cloud, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^] .
