---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Estas limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure. 
---
= Limitaciones conocidas de Cloud Volumes ONTAP en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las siguientes limitaciones conocidas son específicas de Cloud Volumes ONTAP en Microsoft Azure.  Asegúrese de revisar tambiénlink:reference-limitations.html["Limitaciones de Cloud Volumes ONTAP en todos los proveedores de nube"] .



== Limitaciones en el uso de extensiones de máquinas virtuales de Azure

Cloud Volumes ONTAP no admite extensiones de máquinas virtuales (VM) de Azure porque afectan las operaciones de administración de BlueXP . Durante la implementación, BlueXP evita la instalación de cualquier extensión en sus máquinas virtuales. Si ya hay extensiones instaladas en sus máquinas virtuales de Cloud Volumes ONTAP existentes, comuníquese con el soporte técnico de Microsoft Azure para eliminarlas. Para obtener orientación, consulte el artículo de la base de conocimientos (KB) https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["¿Se pueden instalar Azure VM Management Extensions en Cloud Volume ONTAP?"^]

A partir del 14 de julio de 2025, NetApp enviará correos electrónicos y le notificará en BlueXP si se detectan extensiones de VM en sus VM de Cloud Volumes ONTAP .



== Limitaciones de la caché Flash

Cloud Volumes ONTAP utiliza el almacenamiento NVMe local en algunos tipos de VM como _Flash Cache_.  Tenga en cuenta esta limitación:

* No se admite el recalentamiento de la caché después de un reinicio.




== Limitaciones de las implementaciones de alta disponibilidad

Los pares de alta disponibilidad (HA) no son compatibles en algunas regiones.

https://bluexp.netapp.com/cloud-volumes-global-regions["Ver la lista de regiones de Azure compatibles"^] .



== Limitaciones de las implementaciones de alta disponibilidad en zonas de disponibilidad única

A partir de Cloud Volumes ONTAP 9.15.1, puede implementar instancias de máquinas virtuales (VM) en modo HA en zonas de disponibilidad (AZ) únicas en Azure.  Para obtener información sobre los criterios que respaldan esta función, consulte https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["Implementar pares de alta disponibilidad en zonas de disponibilidad únicas en Azure"^] .

Si la versión de Cloud Volumes ONTAP es anterior a 9.15.1 o si no se cumple alguna de estas condiciones, se aplica el modelo de implementación anterior que utiliza conjuntos de disponibilidad.  Esto se aplica únicamente a configuraciones de alta disponibilidad (HA).
