---
sidebar: sidebar 
permalink: reference-configs-aws.html 
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package 
summary: Se admiten varias configuraciones de Cloud Volumes ONTAP en AWS. 
---
= Configuraciones compatibles con Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se admiten varias configuraciones de Cloud Volumes ONTAP en AWS.



== Número de nodos admitidos

Cloud Volumes ONTAP está disponible en AWS como un sistema de nodo único y como un par de nodos de alta disponibilidad (HA) para tolerancia a fallas y operaciones no disruptivas.

No se admite la actualización de un sistema de un solo nodo a un par de alta disponibilidad.  Si desea cambiar entre un sistema de un solo nodo y un par de alta disponibilidad, deberá implementar un nuevo sistema y replicar los datos del sistema existente al nuevo sistema.



== Almacenamiento compatible

Cloud Volumes ONTAP admite varios tipos de discos EBS y almacenamiento de objetos S3 para la organización de datos en niveles.  La capacidad máxima de almacenamiento está determinada por la licencia que elija.



=== Soporte de almacenamiento por licencia

Cada licencia admite una capacidad máxima del sistema diferente. La capacidad máxima del sistema incluye almacenamiento basado en disco más almacenamiento de objetos utilizado para la clasificación de datos.  NetApp no ​​admite superar este límite.

[role="tabbed-block"]
====
.Licencias basadas en capacidad
--
[cols="h,d,d"]
|===
|  | Freemium | Licencia basada en capacidad 


 a| 
*Capacidad máxima del sistema* (discos + almacenamiento de objetos) ^1^
| 500 GiB | Flexible ^2^ 


 a| 
*Tipos de discos admitidos*
 a| 
* SSD de propósito general (gp3 y gp2) ^3^,^5^
* SSD de IOPS aprovisionados (io1) ^3^
* HDD con rendimiento optimizado (st1) ^4^




 a| 
*Nivelación de datos fríos en S3*
 a| 
Apoyado

|===
Notas:

. Para un par HA, el límite de capacidad es para todo el par HA.  No es por nodo.  Por ejemplo, si utilizas la licencia Premium, podrás tener hasta 368 TiB de capacidad entre ambos nodos.
. Para algunas configuraciones, los límites de disco impiden que se alcance el límite de capacidad utilizando solo discos.  En esos casos, puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] .  Para obtener información sobre los límites del disco, consultelink:reference-limits-aws.html["límites de almacenamiento"] .
+
Con licencias basadas en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos. La capacidad total escalonada se puede escalar hasta el límite de capacidad del proveedor de la nube. Si bien la licencia no impone restricciones de capacidad, debe seguir las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles.

. El rendimiento de escritura mejorado está habilitado cuando se utilizan SSD con todas las configuraciones de Cloud Volumes ONTAP .
. No se recomienda la organización de datos en niveles de almacenamiento de objetos cuando se utilizan discos duros optimizados para rendimiento (st1).
. Las configuraciones de Cloud Volumes ONTAP en AWS Local Zones solo admiten el tipo de disco SSD de uso general (gp2).  No se admiten otros tipos de discos en Cloud Volumes ONTAP en AWS Local Zones.


--
.Licencias basadas en nodos
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explorar | Estándar PAYGO | Prima de pago por uso | BYOL basado en nodos 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TiB | 10 TiB | 368 TiB ^2^ | 368 TiB por licencia ^2^ 


| Tipos de discos compatibles  a| 
* SSD de propósito general (gp3 y gp2) ^3^,^5^
* SSD de IOPS aprovisionados (io1) ^3^
* HDD con rendimiento optimizado (st1) ^4^




| Agrupación de datos fríos en niveles para S3 | No compatible 3+| Apoyado 
|===
Notas:

. Para un par HA, el límite de capacidad es para todo el par HA.  No es por nodo.  Por ejemplo, si utilizas la licencia Premium, podrás tener hasta 368 TiB de capacidad entre ambos nodos.
. Para algunas configuraciones, los límites de disco impiden que se alcance el límite de capacidad utilizando solo discos.  En esos casos, puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^] .  Para obtener información sobre los límites del disco, consultelink:reference-limits-aws.html["límites de almacenamiento"] .
. El rendimiento de escritura mejorado está habilitado cuando se utilizan SSD con todas las configuraciones de Cloud Volumes ONTAP , excepto PAYGO Explore.
. No se recomienda la organización de datos en niveles de almacenamiento de objetos cuando se utilizan discos duros optimizados para rendimiento (st1).
. Las configuraciones de Cloud Volumes ONTAP en AWS Local Zones solo admiten el tipo de disco SSD de uso general (gp2).


--
====


=== Tamaños de disco admitidos

En AWS, un agregado puede contener hasta 6 discos, todos del mismo tamaño.  Pero si tiene una configuración que admite la función Volumen elástico de Amazon EBS, entonces un agregado puede contener hasta 8 discos. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Obtenga más información sobre la compatibilidad con Elastic Volumes"^]

[cols="3*"]
|===
| SSD de propósito general (gp3 y gp2) | SSD con IOPS aprovisionados (io1) | HDD con rendimiento optimizado (st1) 


 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB


|===


== Cálculo EC2 compatible

Cada licencia de Cloud Volumes ONTAP admite diferentes tipos de instancias EC2.  Para su comodidad, la siguiente tabla muestra la vCPU, la RAM y el ancho de banda para cada tipo de instancia compatible. https://aws.amazon.com/ec2/instance-types/["Debe consultar AWS para obtener los detalles más recientes y completos sobre los tipos de instancias EC2."^] .

Cloud Volumes ONTAP puede ejecutarse en una instancia EC2 reservada o bajo demanda.  No se admiten soluciones que utilizan otros tipos de instancias.

Los anchos de banda que se muestran en la tabla a continuación coinciden con los límites documentados de AWS para cada tipo de instancia.  Estos límites no se alinean completamente con lo que Cloud Volumes ONTAP puede proporcionar.  Para conocer el rendimiento esperado, consulte https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["Informe técnico 4383 de NetApp : Caracterización del rendimiento de Cloud Volumes ONTAP en Amazon Web Services con cargas de trabajo de aplicaciones"^] .

[cols="8*"]
|===
| Licencia | Instancia compatible | CPU virtual | RAM | Caché Flash ^1^ | Ancho de banda de red (Gbps) | Ancho de banda de EBS (Mbps) | Alta velocidad de escritura ^2^ 


| *Explorar o cualquier otra licencia* | m5.xgrande ^6^ | 4 | 16 | No compatible | Hasta 10 | Hasta 4.750 | Compatible (solo nodo único) 


.3+| *Licencia estándar o cualquier otra* | r5.xgrande ^6^ | 4 | 32 | No compatible | Hasta 10 | Hasta 4.750 | Compatible (solo nodo único) 


| m5a.2xlarge | 8 | 32 | No compatible | Hasta 10 | Hasta 2.880 | Apoyado 


| m5.2xgrande ^6^ | 8 | 32 | No compatible | Hasta 10 | Hasta 4.750 | Apoyado 


.22+| *Licencia Premium o cualquier otra* | m5n.2xlarge | 8 | 32 | No compatible | Hasta 25 | Hasta 4.750 | Apoyado 


| r5.2xgrande ^6^ | 8 | 64 | No compatible | Hasta 10 | Hasta 4.750 | Apoyado 


| r5d.2xlarge | 8 | 64 | Apoyado | Hasta 10 | Hasta 4.750 | Apoyado 


| c5d.4xgrande ^6^ | 16 | 32 | Apoyado | Hasta 10 | 4.570 | Apoyado 


| m5.4xgrande ^6^ | 16 | 64 | No compatible | Hasta 10 | 4.750 | Apoyado 


| m5dn.4xlarge | 16 | 64 | Apoyado | Hasta 25 | 4.750 | Apoyado 


| m5d.8xlarge | 32 | 128 | Apoyado | 10 | 6.800 | Apoyado 


| r5.8xlarge | 32 | 256 | No compatible | 10 | 6.800 | Apoyado 


| c5.9xlarge | 36 | 72 | No compatible | 10 | 9.500 | Apoyado 


| c5d.9xlarge | 36 | 72 | Apoyado | 10 | 9.500 | Apoyado 


| c5n.9xlarge | 36 | 96 | No compatible | 50 | 9.500 | Apoyado 


| c5a.12xlarge | 48 | 96 | No compatible | 12 | 4.750 | Apoyado 


| c5.18xlarge | 64 ^4^ | 144 | No compatible | 25 | 19.000 | Apoyado 


| c5d.18xlarge | 64 ^4^ | 144 | Apoyado | 25 | 19.000 | Apoyado 


| m5d.12xlarge | 48 | 192 | Apoyado | 12 | 9.500 | Apoyado 


| m5dn.12xlarge | 48 | 192 | Apoyado | 50 | 9.500 | Apoyado 


| c5n.18xlarge | 64 ^4^ | 192 | No compatible | 100 | 19.000 | Apoyado 


| m5a.16xlarge | 64 | 256 | No compatible | 12 | 9.500 | Apoyado 


| m5.16xlarge | 64 | 256 | No compatible | 20 | 13.600 | Apoyado 


| r5.12xgrande ^3^ | 48 | 384 | No compatible | 10 | 9.500 | Apoyado 


| m5dn.24xlarge | 64 ^4^ | 384 | Apoyado | 100 | 19.000 | Apoyado 


| m6id.32xlarge | 64 ^4^ | 512 | Apoyado | 50 | 40.000 | Apoyado 
|===
. Algunos tipos de instancias incluyen almacenamiento NVMe local, que Cloud Volumes ONTAP utiliza como _Flash Cache_.  Flash Cache acelera el acceso a los datos a través del almacenamiento en caché inteligente en tiempo real de datos de usuario leídos recientemente y metadatos de NetApp .  Es eficaz para cargas de trabajo intensivas de lectura aleatorias, incluidas bases de datos, correo electrónico y servicios de archivos.  La compresión debe estar deshabilitada en todos los volúmenes para aprovechar las mejoras de rendimiento de Flash Cache. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Obtenga más información sobre Flash Cache"^] .
. Cloud Volumes ONTAP admite una alta velocidad de escritura con la mayoría de los tipos de instancias cuando se utiliza un par HA.  Se admite alta velocidad de escritura con todos los tipos de instancias cuando se utiliza un sistema de nodo único. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Obtenga más información sobre cómo elegir una velocidad de escritura"^] .
. El tipo de instancia r5.12xlarge tiene una limitación conocida con la capacidad de soporte.  Si un nodo se reinicia inesperadamente debido a un pánico, es posible que el sistema no recopile los archivos principales que se usan para solucionar problemas y encontrar la causa raíz del problema.  El cliente acepta los riesgos y los términos de soporte limitados y asume toda la responsabilidad de soporte si se produce esta condición.  Esta limitación afecta a los pares de HA recientemente implementados y a los pares de HA actualizados desde 9.8.  La limitación no afecta a los sistemas de nodo único recientemente implementados.
. Si bien estos tipos de instancias EC2 admiten más de 64 vCPU, Cloud Volumes ONTAP solo admite hasta 64 vCPU.
. Cuando elige un tipo de instancia EC2, puede especificar si es una instancia compartida o una instancia dedicada.
. Las zonas locales de AWS son compatibles con las siguientes familias de tipos de instancias EC2 con tamaños desde xlarge hasta 4xlarge: M5, C5, C5d, R5 y R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2["Debe consultar AWS para obtener los detalles más recientes y completos sobre los tipos de instancias EC2 compatibles en zonas locales."^] .
+
Estos tipos de instancias no admiten alta velocidad de escritura en las zonas locales de AWS.





=== Las instancias c4, m4 y r4 ya no son compatibles

Cloud Volumes ONTAP ya no admite los tipos de instancias EC2 c4, m4 y r4 en AWS.  Si su sistema se ejecuta en una instancia c4, m4 o r4, cámbielo a una instancia c5, m5 o r5.  No puede actualizar a esta versión hasta que cambie el tipo de instancia.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Aprenda a cambiar el tipo de instancia EC2 para Cloud Volumes ONTAP"^] .

Para obtener más información, consulte:

* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Converting_an_AWS_Xen_CVO_instance_to_Nitro_KVM["Artículo de la base de conocimientos (KB): Conversión de una instancia de AWS Xen CVO a Nitro KVM"^]
* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error["Artículo de Knowledge Base: No se puede cambiar el tipo de instancia de r4 a r5 con un error de recuento de discos"^]
* link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Obtenga más información sobre el fin de la disponibilidad y el soporte para estos tipos de instancias"^]




== Regiones compatibles

Para obtener soporte para la región de AWS, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"^] .
